language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

env:
  global:
    # Coverity
    - secure: "qvveM69a744HZDGF4u4SF2BioI5yWguMbdUrD0RFW8jH7Ie4UPDshMhQHVzzJNPCUUe9XU100EJ12lwYGBf5WJ5hHfHg1tbANkbjQfI6AYl/0cAOIdSJmFwCbuSHqdSHLZZEnRTeZcuWHdEnosqTeNaoslMuuR/GqaX2lweZkoslRQy5zjCAmEMSceg8vFA8fekpnSsXMgj59aDQpi7JBp9Xttirx8tgUF4VGhiqSSiBXV3yq4YlGPur2RVpqQSayr9tctbI7mI3be3zkKl8DveRc9hjpDyhp5oNk8rIaYdzBrXakGNP/fx10KiQfFK2+DUlXqp3WJawf/VuEmuHwawVjX0pusSjkS8fH/xS/ObgqOuvTRiCew55oxDegogfZCXxmxJJ6znfKXvDdS/B3teiPkfgjoejHGDJOkYtz+JqAflRrQv8jOHw/NDHLKnbB03by7LPZuBxKnc7j/pa2IsX4MVlMqNxOoUKHZ+w/xsEDuFbnJfAuOYc1e/seByByb0PhTTmqnOEq14Eyzf+vNt8mb6/D63C4XyU+wm23bABeRclP9R/5uENeGaa1sI7xrHnSC/5mMtUyKiIvIvZZhxJ8pnzLNfiOZloilYL+ihhLsTaHgVKqQXpeX3VdYAfZZ/x6+A3XV2jYzD7b8JVR2YL75dc9s4eWcrnEFzauAU="

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/
    - $HOME/.cache/ci-support
    - $HOME/.cache/lint
before_cache:
  - find $HOME/.gradle -name "*.lock" -exec rm {} \;
  - rm -rf $HOME/.gradle/caches/[1-9]*

addons:
  coverity_scan:
    project:
      name: "alescdb/LauncherTV"
      description: "Android Simple TV Launcher"
    notification_email: alescdb@users.noreply.github.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: coverity_scan

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    
  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - mkdir -p $HOME/.cache/lint
  - chmod 0755 ./gradlew
script:
  - ./gradlew checkStyle build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
after_success: ./gradlew coveralls
