language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

env:
  global:
    # Coverity
    - secure: "BmQOYUOcXeEQmb2zNZuolLDG97vjycuP4m2Nt5Fm7CkXLnJKNN1wV6rBLOkqEi1eAbm9rMXjX1FP2jpr5k1FPqLuF4i3zL8eSSPHt6yNtssRn9243cIPot3NOpxEe8TwyF+G99FZmRnUspcKo0dFVqvgiVNUr9gpb7BBJkr6CO9kj9LM19YzNQLMjuqCqv9DZKzU3mlyfwH6zlkYQLfJNJXhEziaNwIc6CW07WAnSiWXyyXriH1LQ7bH+zRvLJmT7TmMkljJQgBNY2aQURTHgaLWAzQibpk9xqBr4gJliXPuC6ZoR69aSv6tE5iROgSjDmGgrfHGZ2C6bVa2HGac+FYDJfU8h8kd1eeU8ky46cYpH1zStEB+CBHoDZhfNFJ21tfEaAHNWEG9n9fbXRQlvnprLR2Job+3aTHLhmXuhqWTfICW4FsoA70+TkLiYyhBX4FytgASUkseJp74V1GMGdLwXXZoBeNKlvoljjDCyjHwK4JpABbnifK8dlljPrjHOd5tvX7AeEuYB/12GeNk7gi59rjb5YO53FOG2R0amUVIm71QCRjojYTM9SYjAHsBfXxuUopxXL8wQzw3j7v31wfEBwJvdlHArsRBn2s5e7P3FRXf7rHgL3I5Wby57phGvXyWkQojcCMcB/b+9IoKO3x1EdY3erPAh6ewklgSCfA="

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/
    - $HOME/.cache/ci-support
    - $HOME/.cache/lint
before_cache:
  - find $HOME/.gradle -name "*.lock" -exec rm {} \;
  - rm -rf $HOME/.gradle/caches/[1-9]*

addons:
  coverity_scan:
    project:
      name: "alescdb/LauncherTV"
      description: "Android Simple TV Launcher"
    notification_email: alescdb@users.noreply.github.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: master

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - mkdir -p $HOME/.cache/lint
  - chmod 0755 ./gradlew
script:
  - ./gradlew checkStyle build connectedCheck

after_failure:
	- "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
	
after_success:
	- ./gradlew coveralls
