language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

env:
  global:
    - CI_NAME=travis-ci
    # Coverity
    - secure: "Y+hGdxU2kf/MF3wC7g4v8qPfa7X0Mhj7YGsBJQckNcTxev5I4gO0BUR/qRezyZyE/ZNRcoSpnCnNAtXwnubJ64HZh3alzvPOiNtuixVW9HNsjPq+34arWev40JDA1Rxn7sMTGk75CthEbjaXS6Y9toWvUEsgHbIwyGkBH8VintKaqO1ih4XR2jaoHD+O4q96NMNIQENK95JA3RIcShaxWWXiOevSaHuiPLMNhip8VB/K4qXLlmXZerfgbflQ/MKgGXCR7WvO0Bppyl2J8Xus8WVVKHotzubbeUWDUmnMRvRGQxQTk4PePZ2vKnqUkwnyIm/aBcA0Z8uO/TsVV3E6gv0dDNEYD7b++H8CSYgd6GVykyr/VXxJ+vXQIlrucC/ZF+7MfIEhtdhYiF4ydwnzEqrz769b8BuQYQ5x9DDV8uYyYeROkN1Bsnso3TUaMhtb7P9eUueSm8czPB3YCL59FPpUGF83Z2LNeWiiRrQMGV2L4PmW5//zx0us3hub3qOo+iaWXRulpsV/Rz25vaegW0F91BqHeB+HICRUhryT2EWj4Uqv2Rj7ufzDPthpXWkMSznM/WKtyAzEe2gT/a/BvcH00ya1HkbBSKX2hF12ueOEp9qyFTm7EojvbUAH2k3Hyvbhe2UFXX1zGvNPQnG28gGcjLeUCfpiQ7s5TIvhn3Q="

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/
    - $HOME/.cache/ci-support
    - $HOME/.cache/lint
before_cache:
  - find $HOME/.gradle -name "*.lock" -exec rm {} \;
  - rm -rf $HOME/.gradle/caches/[1-9]*

addons:
  coverity_scan:
    project:
      name: "alescdb/LauncherTV"
      description: "Android Simple TV Launcher"
    notification_email: alescdb@users.noreply.github.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: master

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - mkdir -p $HOME/.cache/lint
  - chmod 0755 ./gradlew
script:
  - ./gradlew checkStyle build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
after_success: ./gradlew coveralls
