language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

env:
  global:
    # Coverity
    - secure: "cDqOwHHZGUCqf1YqbTvhr+0WFM8ubieMcd1ytIMrKSVFS0z0tgM+dG+/YGUb0m4YNLdMqXU+k07y3O96O2swKDuPzUT37usx922njoPW/y01oh9d1suBNRxffoun4zmzFywT0QdhvD1UY3WV05npHZdqHwH9L61Wc/3eWi3RdYXCOTWSUXN1jJpfux5wvyd0EboapYktAnY5gE9Om+U9c+yclXDflIpSEnftYFwARqXlsh+1qN9piZNFktJGKB7UiByuQsfwfU2UXmMrruO7MOulmLYLcRB9Li9LKqqgPGn5+gaKN/ZT7cQceIpigzGTzEhRHsXdigCcCa6axk6G9dm6ByaRkayWFHyt1BDHdgG8/U+kUUeFqKu1QY539/nihGm6fj+IB/xmRG1YszNArtxvBUYZoreM6SwzMVGUXt3208OhLrFqOOHg1YLWCCP9bY9iFKll6aoeC3ntsm/m9GtUIa5P8eO5/6X+dE10bTMQ5k4vAKMVL+FSLB3Afu8UmTzFJSd59fzWxtNOnMvVZt0/aOGQuExkiZgymbyhMm+JjOdZNx9O5Pn/ri7q+XyN9BpmhVJ+FGIhP/Zkpv/H5fcZDLOdCRWpDitCC5YWZeZRrHlwhreYrnu95yixslAMeNGws8DQTOZfS021pMXIo7GsnBYAx6WsUbc3mW71n6w="

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/
    - $HOME/.cache/ci-support
    - $HOME/.cache/lint
before_cache:
  - find $HOME/.gradle -name "*.lock" -exec rm {} \;
  - rm -rf $HOME/.gradle/caches/[1-9]*

addons:
  coverity_scan:
    project:
      name: "alescdb/LauncherTV"
      description: "Android Simple TV Launcher"
    notification_email: alescdb@users.noreply.github.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: master

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - mkdir -p $HOME/.cache/lint
  - chmod 0755 ./gradlew
script:
  - ./gradlew checkStyle build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
after_success: ./gradlew coveralls
