language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    
  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - mkdir -p $HOME/.cache/lint
  - chmod 0755 ./gradlew
script:
  - ./gradlew checkStyle build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
